### ISSUE TITLE
The map which won doesn't get highlighted

### ISSUE THREAD

**Issue by garnichtpascal** [Partly-Adequate/pam-dark-votescreen#1]
Hey there, I'm playing TTT2 with the Garry's Mod January 2023 version. All of these addons are part of my collection:
PAM
PAM Manager
PAM Dark Votescreen
PAM Random Option
PAM Gamemode Voting
PAM Compatibility Pack
PAM RTV
Pacoman UI

However, the winning map doesn't get highlighted or anything. The menu just re-opens when the voting is over, without showing which map won.
![grafik](https://user-images.githubusercontent.com/24548299/228618342-21db486d-7ca1-425b-b5f1-b6a8dc1b41bd.png)

**Comment by Reispfannenfresser** [comment]
Thank you for reporting the issue.
I finally found some time to fix this bug and now it's gone 👍🏻 
I just pushed the update to the workshop.
